// ================================================================
// types/database.ts
// Auto-generated stub — replace with: npx supabase gen types typescript --local
// This file matches the shape generated by the Supabase CLI
// ================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          name: string
          avatar_url: string | null
          role: string
          subscription_status: string
          subscription_plan: string | null
          subscription_expires_at: string | null
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          org_id: string | null
          country_code: string
          currency: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          avatar_url?: string | null
          role?: string
          subscription_status?: string
          subscription_plan?: string | null
          subscription_expires_at?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          org_id?: string | null
          country_code?: string
          currency?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      scores: {
        Row: {
          id: string
          user_id: string
          score: number
          date: string
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          score: number
          date: string
          notes?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['scores']['Insert']>
      }
      charities: {
        Row: {
          id: string
          name: string
          description: string | null
          logo_url: string | null
          website_url: string | null
          registered_number: string | null
          is_active: boolean
          total_contributed: number
          is_deleted: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          logo_url?: string | null
          website_url?: string | null
          registered_number?: string | null
          is_active?: boolean
          total_contributed?: number
          is_deleted?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['charities']['Insert']>
      }
      draws: {
        Row: {
          id: string
          month: number
          year: number
          mode: string
          winning_numbers: number[]
          total_pool: number
          jackpot_amount: number
          prize_4match: number
          prize_3match: number
          jackpot_rolled_over: boolean
          rollover_from_draw_id: string | null
          rollover_amount: number
          charity_id: string | null
          charity_contribution: number
          charity_percentage: number
          participant_count: number
          status: string
          run_by: string | null
          run_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          month: number
          year: number
          mode: string
          winning_numbers: number[]
          total_pool?: number
          jackpot_amount?: number
          prize_4match?: number
          prize_3match?: number
          jackpot_rolled_over?: boolean
          rollover_from_draw_id?: string | null
          rollover_amount?: number
          charity_id?: string | null
          charity_contribution?: number
          charity_percentage?: number
          participant_count?: number
          status?: string
          run_by?: string | null
          run_at?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['draws']['Insert']>
      }
      draw_winners: {
        Row: {
          id: string
          draw_id: string
          user_id: string
          tier: string
          match_count: number
          matched_numbers: number[]
          user_scores: number[]
          amount: number
          paid_out: boolean
          created_at: string
        }
        Insert: {
          id?: string
          draw_id: string
          user_id: string
          tier: string
          match_count: number
          matched_numbers: number[]
          user_scores: number[]
          amount?: number
          paid_out?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['draw_winners']['Insert']>
      }
      winner_proofs: {
        Row: {
          id: string
          draw_winner_id: string
          user_id: string
          draw_id: string
          proof_url: string
          storage_path: string
          file_name: string | null
          file_size: number | null
          mime_type: string | null
          status: string
          admin_note: string | null
          reviewed_by: string | null
          reviewed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          draw_winner_id: string
          user_id: string
          draw_id: string
          proof_url: string
          storage_path: string
          file_name?: string | null
          file_size?: number | null
          mime_type?: string | null
          status?: string
          admin_note?: string | null
          reviewed_by?: string | null
          reviewed_at?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['winner_proofs']['Insert']>
      }
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string | null
          country_code: string
          billing_email: string | null
          plan: string
          seat_limit: number | null
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          subscription_status: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          logo_url?: string | null
          country_code?: string
          billing_email?: string | null
          plan?: string
          seat_limit?: number | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>
      }
      campaigns: {
        Row: {
          id: string
          name: string
          start_date: string | null
          end_date: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          start_date?: string | null
          end_date?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['campaigns']['Insert']>
      }

      campaigns: {
        Row: {
          id: string
          name: string
          start_date: string | null
          end_date: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          start_date?: string | null
          end_date?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['campaigns']['Insert']>
      }

      audit_logs: {
        Row: {
          id: string
          actor_id: string | null
          action: string
          entity_type: string
          entity_id: string | null
          old_values: Json | null
          new_values: Json | null
          payload: Json | null
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          actor_id?: string | null
          action: string
          entity_type: string
          entity_id?: string | null
          old_values?: Json | null
          new_values?: Json | null
          payload?: Json | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['audit_logs']['Insert']>
      }
    }
    Functions: {
      current_user_role: { Args: Record<never, never>; Returns: string }
      get_draw_participants: {
        Args: { p_month: number; p_year: number }
        Returns: Array<{ user_id: string; scores: number[] }>
      }
      get_admin_stats: {
        Args: Record<never, never>
        Returns: Array<{
          total_active_members: number
          pending_proofs: number
          total_charity_contributed: number
          current_jackpot: number
        }>
      }
      increment_charity_contribution: {
        Args: { p_charity_id: string; p_amount: number }
        Returns: void
      }
      log_audit_event: {
        Args: {
          p_actor_id: string | null
          p_action: string
          p_entity_type: string
          p_entity_id?: string | null
          p_old_values?: Json | null
          p_new_values?: Json | null
          p_payload?: Json | null
        }
        Returns: string
      }
    }
    Enums: Record<never, never>
  }
}
